package_assets: always
package_path: ../public/assets
embed_assets: on
compress_assets: on
gzip_assets: off
javascript_compressor: closure

javascripts:
  fractal_lab:
    - public/javascripts/jquery-1.5.min.js
    - public/javascripts/underscore-min.js
    - public/javascripts/super_slider.js
    - public/javascripts/color.js
    - public/javascripts/color_picker.js
    - public/javascripts/gl_quad.js
    - public/javascripts/camera.js
    - public/javascripts/fractal_lab.js
    - public/javascripts/sql_adapter.js
    - public/javascripts/sql_store.js
    - public/javascripts/local_storage_adapter.js
    - public/javascripts/preset_manager.js
    - public/javascripts/fractal_library.js
    - public/javascripts/fps.js
    - public/javascripts/application.js

stylesheets:
  fractal_lab:
    - public/stylesheets/color_picker.css
    - public/stylesheets/super_slider.css
    - public/stylesheets/fractal_lab.css

